app:
  env: development
  port: 3000   
  middleware:
    http:
      urlencoded:
        parameterLimit: 10
        extended: true
      json:
        limit: 1mb 
  todo:
    route: /todos
    storage:
      mapper:
        type: electrodb
        config:
          table: todos
      database:
        type: dynamodb
        config: {}