app:
  options:
    mode: serverless
    env: development
    port: 8080   
  middleware:
    http:
      urlencoded:
        parameterLimit: 10
        extended: true
      json:
        limit: 1mb 
  todo:
    route: /todos
    storage:
      mapper:
        type: electrodb
        config:
          table: todos
      database:
        type: dynamodb
        config: {}
