name: SAM Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  login-to-amazon-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          region: us-east-1
      - name: Build, tag, and push docker image to Amazon ECR Public
        run: |
          echo "registry: {{ steps.login-ecr-public.outputs.registry }}"
  
